### ISSUE TITLE
Unable to compile this library

### ISSUE THREAD

**Issue by locomotive-crypto** [ladnir/cryptoTools#22]
locomotive@locomotive-VirtualBox:~/sknn/libOTe/cryptoTools$ make
[  2%] Built target sha_asm
[  5%] Building CXX object cryptoTools/CMakeFiles/cryptoTools.dir/Network/Channel.cpp.o
In file included from /home/locomotive/sknn/libOTe/cryptoTools/cryptoTools/Network/Channel.h:5:0,
                 from /home/locomotive/sknn/libOTe/cryptoTools/cryptoTools/Network/Channel.cpp:1:
/home/locomotive/sknn/libOTe/cryptoTools/cryptoTools/Network/SocketAdapter.h: In member function ‘virtual void osuCrypto::BoostSocketInterface::send(osuCrypto::span<boost::asio::mutable_buffer>, bool&, osuCrypto::u64&)’:
/home/locomotive/sknn/libOTe/cryptoTools/cryptoTools/Network/SocketAdapter.h:166:25: error: no match for ‘operator!=’ (operand types are ‘boost::system::error_code’ and ‘int’)
             error = (ec != 0);
                      ~~~^~~~
compilation terminated due to -Wfatal-errors.
cryptoTools/CMakeFiles/cryptoTools.dir/build.make:354: recipe for target 'cryptoTools/CMakeFiles/cryptoTools.dir/Network/Channel.cpp.o' failed
make[2]: *** [cryptoTools/CMakeFiles/cryptoTools.dir/Network/Channel.cpp.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'cryptoTools/CMakeFiles/cryptoTools.dir/all' failed
make[1]: *** [cryptoTools/CMakeFiles/cryptoTools.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ladnir** [comment]
when I go to [SocketAdapter.h:166](https://github.com/ladnir/cryptoTools/blob/master/cryptoTools/Network/SocketAdapter.h#L166) I don't see the offending line of code. Is this code you wrote?

**Comment by locomotive-crypto** [comment]
No, I don't do anything.

**Comment by ladnir** [comment]
well not sure how to help you. That line of code is not in the repo https://github.com/ladnir/cryptoTools/search?q=error+%3D+%28ec+%21%3D+0%29%3B

**Comment by locomotive-crypto** [comment]
Thanks, It may be the problem about others libraries. I use this library as the third-party library for compiling the `secure-kmean-clustering`: https://github.com/osu-crypto/secure-kmean-clustering
