### ISSUE TITLE
few issues with the cmake and with the readme.md

### ISSUE THREAD

**Issue by haibren** [ladnir/cryptoTools#23]
1.
In the Unix subsection in the install section in readme.md , there is a call to `make` right after installing boost. But it did not succeed for me without applying cmake first. (on macos)

[Btw, the boost.get also fails on macos, and it only works after commenting out lines as described here: https://github.com/zcash/zcash/issues/4333 . - This is not an issue in cryptoTools obviously.]

2.
Once again in the readme file, it says the binary name is ./frontend_libOTe . But that's just a copy-paste issue from the libOTe project. Instaed it should be ./frontend_cryptoTools/frontend_cryptoTools

3.
Trying `make install` also fails. It looks for a file cryptoools-config.cmake in the project root directory. There is no such file there. But there is a file in another directory named cryptoToolsconfig.cmake  (no dash, and capital T). Could it be this file? Seemed to do some install process on my laptop

**Comment by ladnir** [comment]
yes, thanks for opening this, I've been a bit slow at fixing these but will soon.

**Comment by ladnir** [comment]
updated boost so thats should be fixed. The readme is now a bit more accurate. And i removed the offending line for the install error. Didn't test the correctness of install though.
