### ISSUE TITLE
can't find config.h in install destionation directory

### ISSUE THREAD

**Issue by zhanglei486** [ladnir/cryptoTools#26]
CMakeList.txt
configure_file(cryptoTools/Common/config.h.in "cryptoTools/Common/config.h" )
shoud add ${PROJECT_SOURCE_DIR}
configure_file(cryptoTools/Common/config.h.in "${PROJECT_SOURCE_DIR}/cryptoTools/Common/config.h" )

**Comment by ladnir** [comment]
the config file is placed in the build directory. This is to support multiple build configurations. If you want it in the source dir, then you can manually to an in-source build.

cmake . 
make -j
