### ISSUE TITLE
‘Expects’ was not declared 

### ISSUE THREAD

**Issue by L-coder148** [ladnir/cryptoTools#30]
![image](https://user-images.githubusercontent.com/75669641/140773423-526532d4-ab21-4b1b-948c-7afb1c2a98fa.png)

**Comment by L-coder148** [comment]
hello，I have installed the [microsoft/GSL](https://github.com/microsoft/GSL) into the default path:`/usr/local`, and add the `#include <gsl/gsl> ` into `IOBuffer.h`, but I do not link the library `gsl`. then I run make seccessfully.
I run the `./frontend_cryptoTools -u` with the following result.
![image](https://user-images.githubusercontent.com/75669641/140849592-b3cfc2af-d78f-4067-bc19-25b78d4c53d0.png)
I run the `./frontend_cryptoTools -tut` with the following two results(sometimes hangs,sometimes No buffer ). I do not know whether the two results are all right. but I see the `Network.cpp ` points that `By default, ios will print when things so wrong such as a bad buffer size`
![image](https://user-images.githubusercontent.com/75669641/140849636-1746de78-8d49-47ba-9a1d-695776594367.png)
![image](https://user-images.githubusercontent.com/75669641/140850293-dfc9e0c4-c33a-470f-a8cd-b3db9802d507.png)

**Comment by ladnir** [comment]
Yes, I recently removed the gls. Gls shouldnt be required and if it is, then that's a bug on my end. I'll investigate. 

I haven't run the tutorial is awhile, I'll check it.

**Comment by ladnir** [comment]
The compile error should be fixed in master.

**Comment by ladnir** [comment]
ok, the tutorial should also work now. There was some bug with the "BasicSocket" example. I just removed it from the tutorial ha. As far as I know, no one uses it anyways.

**Comment by L-coder148** [comment]
Thanks for your reply and patience. I found another strange problem.
I install cryptotools successfully, in `cryptoTools\Common\Defines.h`, it includes the header file `"cryptoTools/Common/config.h"`,but there is no `config.h` but `config.h.in`, but it can be compiled successfully.

But when I compile my project(demo) with library `cryptotools`,I put the library under the project `demo`, it occurs the following error:
![image](https://user-images.githubusercontent.com/75669641/140868671-9005904b-8933-43d1-9150-366669a04561.png)

**Comment by ladnir** [comment]
Hmm, yeah, likely another bug on my end. I haven't tested install with just cryptoTools. Usually I install via libOTe. As a temporary fix, the config.h file will be written to the binary directory, likely out/linux/cryptoTools/config.h

You can copy this to the install dir. I'll debug the install tomorrow.

**Comment by L-coder148** [comment]
ok,thank you

**Comment by ladnir** [comment]
im not getting this error. Seems the config file is installed correctly.

![image](https://user-images.githubusercontent.com/2809762/140990156-08303ad3-8694-45fe-b01b-60523802dba2.png)

**Comment by L-coder148** [comment]
Thanks. I will reinstall it later.
By the way, is there a interface to get the `high_u64`or `low_u64` from a `block`. For example,I want to get the  `high_u64` of `m`,that is `5`. 
`block m=toBlock(5,0);`

**Comment by ladnir** [comment]
`block::as<u64>()[0]` for low and `block::as<u64>()[1]` for high.
