### ISSUE TITLE
Build error: no type named 'const_iterator' in 'std::span'

### ISSUE THREAD

**Issue by morebtcg** [ladnir/cryptoTools#31]
When building the cryptoTools without span-lite, i got error:

> In included file: no type named 'const_iterator' in 'std::span<osuCrypto::block, 18446744073709551615>'clang(typename_nested_not_found)
> [MatrixView.h(16, 32): ]()Error occurred here
> [Matrix.h(16, 27): ]()In instantiation of template class 'osuCrypto::MatrixView<osuCrypto::block>' requested here
> [KkrtNcoOtReceiver.h(34, 23): ]()In instantiation of template class 'osuCrypto::Matrix<osuCrypto::block>' requested here

Because const_iterator in std::span was removed as a result of [LWG3320](https://wg21.link/lwg3320).

May i pull request to fix it?

**Comment by ladnir** [comment]
sure. thanks.
