### ISSUE TITLE
How to select prime curve by curveID

### ISSUE THREAD

**Issue by yellow123Nike** [ladnir/cryptoTools#36]
The first figure contains the elliptic curve included in the RElic
![image](https://github.com/ladnir/cryptoTools/assets/37546857/80a0547e-265b-4ae0-945f-c04b3f520908)
The second graph is selecting an elliptic curve by curveID, but ep_param_get() returns 12, and if curveID is not the selected 12, the SECG_K256 curve is used
![image](https://github.com/ladnir/cryptoTools/assets/37546857/39049070-1026-4200-a0e5-2b7176177c34)
But I want to select CURVE_25519, so what should I select？

**Comment by ladnir** [comment]
fixed in master. YOu now pass the relic value as the `curveID`
