### ISSUE TITLE
Question About CuckooHash Params

### ISSUE THREAD

**Issue by zhouxv** [ladnir/cryptoTools#37]
In **cryptoTools/Common/CuckooIndex.cpp**,  the function _selectParams_ is used to set CuckooHash Params，
what is the basis for setting the parameters, and are there any research papers on the relevant experimental conclusions and formulas?

For example, is there rigorous evidence supporting the lines in the figure below,
![image](https://github.com/ladnir/cryptoTools/assets/15267852/8246c2e4-bdc8-450c-bf61-57b8f246a3a1)
or which article proposed the formula for calculating the statSecParam parameter?
![image](https://github.com/ladnir/cryptoTools/assets/15267852/da24ddff-b7cc-4ad0-96a9-5a48587ec76c)

Thank you for your time and assistance. I truly appreciate your help in addressing my questions. Looking forward to hearing from you soon.

**Comment by ladnir** [comment]
i believe this is the more detailed description https://eprint.iacr.org/2018/579.pdf

but i think i might have updated the parameters since that paper was published. The methodology is the same though.

**Comment by ladnir** [comment]
I think the code to run the experiments is here. https://github.com/ladnir/cryptoTools/tree/7c3fed414d128e7ee9d2aad961731ab3344bd0d0/frontend_cryptoTools/cuckoo 

although it might be out of date.

**Comment by zhouxv** [comment]
Thanks for your response.^_^
I will do some experiments.
