### ISSUE TITLE
‘osuCrypto::Sodium’ has not been declared

### ISSUE THREAD

**Issue by The-Miracl** [ladnir/cryptoTools#39]
Why does this error occur？Thank you
/root/PSU_gai/BloomFilter/bloom_filter.h:17:18: error: ‘osuCrypto::Sodium’ has not been declared
   17 | using osuCrypto::Sodium::Rist25519;

**Comment by ladnir** [comment]
You need to make sure you include cryptoTools/Crypto/Sodium.h and build cryptoTools with sodium enabled.

**Comment by The-Miracl** [comment]
Thank you，one more question, but how can i build cryptoTools with sodium enabled?

**Comment by ladnir** [comment]
ah, i guess the readme is missing this. you call `python build.py --sodium`.

**Comment by The-Miracl** [comment]
Thank you !
