### ISSUE TITLE
the problem about v1.5.0

### ISSUE THREAD

**Issue by programmerpyh** [ladnir/cryptoTools#40]
The address of boost is outdated in the /thirdparty/linux/boost.get, please change it.

This problem not only make the Build process fail, but also affect the "libOTe" repository's Build process

The useful address is "https://boostorg.jfrog.io/artifactory/main/release/1.69.0/source/boost_1_69_0.tar.bz2"

**Comment by ladnir** [comment]
you are using an old version of cryptoTools, not sure what you want me to do ;) 

if you are using libOTe 1.5, maybe try upgrading to 1.6 and if theres still a problem ill consider fixing it.

**Comment by programmerpyh** [comment]
But many PSI code like KKRT16 in linux still use the v1.5.0 of cryptoTools, so I really want you to change the thirdparty/linux/boost.get document. You can see this document, and you will find the URL of boost is 404.

**Comment by ladnir** [comment]
My advice for psi is to use libPSI or Vole Psi and if you want the batch oprf to use libOTe.

You can also create a pull request to kkrt to upgrade it to libOTe 1.6 but I'm not going to maintain it myself.
