### ISSUE TITLE
CMake Error when executing " python3 build.py --setup --boost"

### ISSUE THREAD

**Issue by cdc94** [ladnir/cryptoTools#43]
What can I do to solve the following cmake error?

CMake Error at out/coproto/cmake/buildOptions.cmake:55 (message):
  Unsupported c++ version.  COPROTO_CPP_VER=17
Call Stack (most recent call first):
  out/coproto/CMakeLists.txt:19 (include)

**Comment by ladnir** [comment]
the simplest fix is to use c++20. Does that work for you? I had intended to keep support for older versions but thats currently broken when you want to use boost.

**Comment by ladnir** [comment]
should work now. defaulted to cpp20
