### ISSUE TITLE
setup failed

### ISSUE THREAD

**Issue by kinghing12345** [ladnir/cryptoTools#6]
I follows the instruction and setup boost + miracle. I met these following issues. Have you ever see it before. I am using VS 2017.

![image](https://user-images.githubusercontent.com/36166284/35817157-473c7baa-0a62-11e8-8440-56ab6d5395e8.png)

![image](https://user-images.githubusercontent.com/36166284/35817128-2ae62f6e-0a62-11e8-8a7b-ccd15655534c.png)

**Comment by ladnir** [comment]
Try the fixes here https://github.com/osu-crypto/libOTe

**Comment by ladnir** [comment]
If miracl still does not work manually open the solution in visual studio and see what's going wrong.

**Comment by ladnir** [comment]
inactive
