### ISSUE TITLE
Bug in Timer

### ISSUE THREAD

**Issue by AMarcedone** [ladnir/cryptoTools#8]
Hi, 
I run into this:
https://github.com/ladnir/cryptoTools/blob/4364c7c3dc7bf4f5a7c7d6881aa0ebf904204546/cryptoTools/Common/Timer.cpp#L46
it should be out instead of cout.

**Comment by ladnir** [comment]
I don't agree... There is no such thing as `std::out`.

**Comment by AMarcedone** [comment]
not `std::out`, just `out`. Same as in line 57. 
Otherwise when you do  `myStream << timer`, the "header" gets printed to stdout instead. 

Sorry if this was not clear.

**Comment by ladnir** [comment]
Ha, yes. Face palm ;) kk. I'll fix.

**Comment by AMarcedone** [comment]
No worries, and thanks for maintaining this repo. I find it useful =)

**Comment by ladnir** [comment]
You and I both. Fixed as of 400e50a9036aa300d40664851cef4ff5d03d4d38
