### ISSUE TITLE
abort when calling chl.recv() on BitVector

### ISSUE THREAD

**Issue by ramym1** [ladnir/cryptoTools#9]
Hi, the following code aborts on the receiver side. It works fine when replacing the use of BitVector to vector<u8>. Can you please help me figuring out how to fix this issue?
`
#include <stdio.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>

#include <cryptoTools/Common/BitVector.h>

#include <cryptoTools/Network/Channel.h>
#include <cryptoTools/Network/Session.h>
#include <cryptoTools/Network/IOService.h>

using namespace osuCrypto;
using namespace std;

std::string addr = "localhost";

void sender(){
    setThreadName("Sender");

    // get up the networking
    IOService ios(0);
    Session sess(ios, addr, 1212, EpMode::Client);
    Channel chl = sess.addChannel();

    chl.resetStats();

    BitVector outputBitMap(900);

    // transfer tables and labels
    chl.send(outputBitMap.data(), outputBitMap.size());

    std::cout
            << "      Sent: " << chl.getTotalDataSent() << std::endl
            << "  received: " << chl.getTotalDataRecv() << std::endl << std::endl;

    chl.close();
    sess.stop();
    ios.stop();
    return;
}

void receiver(){
    setThreadName("Receiver");

    // get up the networking
    IOService ios(0);
    Session sess(ios, addr, 1212, EpMode::Server);
    Channel chl = sess.addChannel();

    chl.resetStats();

    // get garbled tables and output maps
    BitVector outputBitMap(900);
    chl.recv(outputBitMap.data(), outputBitMap.size());

    std::cout
        << "      Sent: " << chl.getTotalDataSent() << std::endl
        << "  received: " << chl.getTotalDataRecv() << std::endl << std::endl;
    chl.resetStats();

    chl.close();
    sess.stop();
    ios.stop();
    return;
}

int main(int argc, char** argv) {

	int role = atoi(argv[1]); // 0: send, 1: recv
	role ? receiver() : sender();
}
`

This is the abort message I get:
"malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted"

Thanks a lot.

**Comment by ladnir** [comment]
this is a bug with your code. `BitVector` is "special". 

`u8* BitVector::data()` returns a pointer to the beginning of a *packed* vector of bits. `u64 BitVector::size()` returns how many bits. However, when you call `Channel.send(u8* data, u64 size)` it is expecting an array of `u8`'s that is `size` bytes long. 

So you are passing `size` in units of bits while `Channel` is expecting them in units of bytes.

Change your calls to something like:
```c++
chl.recv(outputBitMap); 
// or 
chl.recv(outputBitMap.data(), outputBitMap.sizeBytes());
```

Note the use of `BitVector::sizeBytes()`

Cheers,
Peter
